In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [16]:
len(df.ChestPainType.unique())

4

In [25]:
uniqueValues = {}
for i in df.columns:
    uniqueValues[i] = (len(df[i].unique()))
uniqueValues = pd.DataFrame(pd.Series(uniqueValues))
uniqueValues.T

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,50,2,4,67,222,2,3,119,2,53,3,2

Age is numeric\
Sex can be done with labelEncoder rather than dummmies as it contains only 2 elements\
ChestPainType should be in dummies\
RestingECG could be experimented but dummies would be preferable\
ST_Slpoe also goes to same format a RestingECG

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [41]:
df.Sex = le.fit_transform(df.Sex)
df.ExerciseAngina = le.fit_transform(df.ExerciseAngina)
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,ATA,140,289,0,Normal,172,0,0.0,Up,0
1,49,0,NAP,160,180,0,Normal,156,0,1.0,Flat,1
2,37,1,ATA,130,283,0,ST,98,0,0.0,Up,0
3,48,0,ASY,138,214,0,Normal,108,1,1.5,Flat,1
4,54,1,NAP,150,195,0,Normal,122,0,0.0,Up,0

In [77]:
new_df = pd.get_dummies(df, columns=['ChestPainType', 'RestingECG', 'ST_Slope'])
new_df

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0.0,0,0,1,0,0,0,1,0,0,0,1
1,49,0,160,180,0,156,0,1.0,1,0,0,1,0,0,1,0,0,1,0
2,37,1,130,283,0,98,0,0.0,0,0,1,0,0,0,0,1,0,0,1
3,48,0,138,214,0,108,1,1.5,1,1,0,0,0,0,1,0,0,1,0
4,54,1,150,195,0,122,0,0.0,0,0,0,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,132,0,1.2,1,0,0,0,1,0,1,0,0,1,0
914,68,1,144,193,1,141,0,3.4,1,1,0,0,0,0,1,0,0,1,0
915,57,1,130,131,0,115,1,1.2,1,1,0,0,0,0,1,0,0,1,0
916,57,0,130,236,0,174,0,0.0,1,0,1,0,0,1,0,0,0,1,0
917,38,1,138,175,0,173,0,0.0,0,0,0,1,0,0,1,0,0,0,1

In [79]:
new_df.drop(['ChestPainType_ASY', 'RestingECG_LVH', 'ST_Slope_Down'], axis=1,  inplace=True)
new_df

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0.0,0,1,0,0,1,0,0,1
1,49,0,160,180,0,156,0,1.0,1,0,1,0,1,0,1,0
2,37,1,130,283,0,98,0,0.0,0,1,0,0,0,1,0,1
3,48,0,138,214,0,108,1,1.5,1,0,0,0,1,0,1,0
4,54,1,150,195,0,122,0,0.0,0,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,132,0,1.2,1,0,0,1,1,0,1,0
914,68,1,144,193,1,141,0,3.4,1,0,0,0,1,0,1,0
915,57,1,130,131,0,115,1,1.2,1,0,0,0,1,0,1,0
916,57,0,130,236,0,174,0,0.0,1,1,0,0,0,0,1,0
917,38,1,138,175,0,173,0,0.0,0,0,1,0,1,0,0,1

In [80]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [88]:
x = new_df.drop(['HeartDisease'], axis = 1)
y = new_df.HeartDisease

In [141]:
x_cols = x.columns
scaler.fit(x[x_cols])
x[x_cols] = scaler.transform(x[x_cols])
x.shape

(918, 15)

SVM \
Logistic \
Random forest

In [147]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
s, r, l = SVC(), RandomForestClassifier(), LogisticRegression()

In [148]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25, random_state=0)

In [149]:
def train(obj, x=xtrain, y=ytrain):
    obj.fit(xtrain, ytrain)

In [150]:
l = [s, r, l]
for i in l:
    train(i)

In [151]:
def getScore(obj, x=xtest, y=ytest):
    score = obj.score(xtest, ytest)
    return score

In [152]:
score = {}
for i in l:
    score[i] = (getScore(i))
score

{SVC(): 0.8521739130434782,
 RandomForestClassifier(): 0.8608695652173913,
 LogisticRegression(): 0.8260869565217391}

In [160]:
from sklearn.decomposition import PCA
pca = PCA(0.90)

In [161]:
x_pca = pca.fit_transform(x)

In [162]:
xtrain, xtest, ytrain, ytest = train_test_split(x_pca, y, test_size=0.25, random_state=0)

In [171]:
xtrain.shape

(688, 11)

In [175]:
pca.explained_variance_ratio_.sum()

0.9121905550886931

In [172]:
s.fit(xtrain, ytrain)

SVC()

In [173]:
s.score(xtest, ytest)

0.8521739130434782

In [177]:
r.fit(xtrain, ytrain)

RandomForestClassifier()

In [178]:
r.score(xtest, ytest)

0.8478260869565217

In [182]:
lr = LogisticRegression()
lr.fit(xtrain, ytrain)

LogisticRegression()

In [183]:
lr.score(xtest, ytest)

0.8478260869565217